### ISSUE TITLE
floyd.yml file!

### ISSUE THREAD

**Issue by whatrocks** [gasgallo/RotNet#1]
Hi! I saw that you checked in your `floyd.yml` file. That's awesome. I just wanted to make sure that you knew that you can use this to "store" your run commands, including mounting datasets, choosing your environment, etc. Then all you'd have to do is type `floyd run` with the floyd-cli tool.

Here's a guide if that's helpful: [https://docs.floydhub.com/floyd_config/](https://docs.floydhub.com/floyd_config/) 👍

**Comment by gasgallo** [comment]
> Hi! I saw that you checked in your `floyd.yml` file. That's awesome. I just wanted to make sure that you knew that you can use this to "store" your run commands, including mounting datasets, choosing your environment, etc. Then all you'd have to do is type `floyd run` with the floyd-cli tool.
> 
> Here's a guide if that's helpful: https://docs.floydhub.com/floyd_config/

Thanks for the suggestion!
